;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="StateTree.Alerted",DevComment="")
+GameplayTagList=(Tag="StateTree.Chase",DevComment="")
+GameplayTagList=(Tag="StateTree.Dance",DevComment="")
+GameplayTagList=(Tag="StateTree.Debug",DevComment="")
+GameplayTagList=(Tag="StateTree.Detected",DevComment="")
+GameplayTagList=(Tag="StateTree.Light",DevComment="")
+GameplayTagList=(Tag="StateTree.Panic",DevComment="")
+GameplayTagList=(Tag="StateTree.Patrol",DevComment="")
+GameplayTagList=(Tag="StateTree.Scared",DevComment="")
+GameplayTagList=(Tag="StateTree.Spooked",DevComment="")

